language: node_js
node_js:
- stable
cache: npm
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: gerson.vfs@gmail.com
  api_key:
    secure: MPAHb8W4ElYKJwcFQ6UOxlPO98hWmtgzacZQrRhCT5fp8oNTNoya6IE4axArsNux7Y4b++TEYx01v0iW/DWQwWg+N9u6Idflo4W3dLZa7/PvsQGHPQlMyjNJXt022odr1LJZzK4n+G9Q8FVC9aRUGHuLeuvkw8eusSSz8Xhb69Eo47PHplZSJ91JqoB85o6g0lvpo07hHH6kpuus5tfS00kXjIpqh7IWBAexcEgmXa72KwNQzEx4W4H5LJ2IWHgQWECm13pBqAgpUYGmUWjJqGhvZKblM6RCoIOjjpSEY0pVC5p5CDMQf9iJIS4LB7DiNVHmK8L2sPXc4nMhUymcJbajZS6rmTiek0pLDKsLK+tvzjMgxpnaNGJ1tC9rH7yd5x6sd1+9Xmo3kPHPby7UfA9e39i+lM6HoakzjAWOEJWK4UAVzkMsucODcPHayFezexwLjZr1XOJ4OT5tO8E7GZ5OITQcFO3dURA2dLGeq+Tt7Ji2oLzESoS+ay0iPdTvXbXF0kzxypLaAjGp0UsXYLGSZi06ynHyIwsEuO3fL4JDoXA+Tfro/Lb6oQYtFqzof5srmv8gKd0O3z3v+4lkGanL3eKgrrs3w4eAO4AgH/p+7dhvc8gYNB/tJe0gRvHP+yacWM3L2/igDLtf9hBaUtKTVe24bGI/HW02ti1M1pA=
  on:
    tags: true
    tag: beta
    branch: master
    repo: nostjs/create-nost-app
